// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BulletData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProtoBulletData {

  /// <summary>Holder for reflection information generated from BulletData.proto</summary>
  public static partial class BulletDataReflection {

    #region Descriptor
    /// <summary>File descriptor for BulletData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BulletDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBCdWxsZXREYXRhLnByb3RvEhBwcm90b19CdWxsZXREYXRhIsoBCgpCdWxs",
            "ZXREYXRhEjsKC3NvaWxkZXJDYW1wGAIgASgOMiYucHJvdG9fQnVsbGV0RGF0",
            "YS5CdWxsZXREYXRhLkNhbXBTdGF0ZRI6CgpidWxsZXRDYW1wGAMgASgOMiYu",
            "cHJvdG9fQnVsbGV0RGF0YS5CdWxsZXREYXRhLkNhbXBTdGF0ZRIRCglzb2ls",
            "ZGVySWQYBCABKAUSEAoIYnVsbGV0SWQYBSABKAUiHgoJQ2FtcFN0YXRlEgcK",
            "A3JlZBAAEggKBGJsdWUQAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoBulletData.BulletData), global::ProtoBulletData.BulletData.Parser, new[]{ "SoilderCamp", "BulletCamp", "SoilderId", "BulletId" }, null, new[]{ typeof(global::ProtoBulletData.BulletData.Types.CampState) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class BulletData : pb::IMessage<BulletData> {
    private static readonly pb::MessageParser<BulletData> _parser = new pb::MessageParser<BulletData>(() => new BulletData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BulletData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoBulletData.BulletDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BulletData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BulletData(BulletData other) : this() {
      soilderCamp_ = other.soilderCamp_;
      bulletCamp_ = other.bulletCamp_;
      soilderId_ = other.soilderId_;
      bulletId_ = other.bulletId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BulletData Clone() {
      return new BulletData(this);
    }

    /// <summary>Field number for the "soilderCamp" field.</summary>
    public const int SoilderCampFieldNumber = 2;
    private global::ProtoBulletData.BulletData.Types.CampState soilderCamp_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtoBulletData.BulletData.Types.CampState SoilderCamp {
      get { return soilderCamp_; }
      set {
        soilderCamp_ = value;
      }
    }

    /// <summary>Field number for the "bulletCamp" field.</summary>
    public const int BulletCampFieldNumber = 3;
    private global::ProtoBulletData.BulletData.Types.CampState bulletCamp_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtoBulletData.BulletData.Types.CampState BulletCamp {
      get { return bulletCamp_; }
      set {
        bulletCamp_ = value;
      }
    }

    /// <summary>Field number for the "soilderId" field.</summary>
    public const int SoilderIdFieldNumber = 4;
    private int soilderId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SoilderId {
      get { return soilderId_; }
      set {
        soilderId_ = value;
      }
    }

    /// <summary>Field number for the "bulletId" field.</summary>
    public const int BulletIdFieldNumber = 5;
    private int bulletId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BulletId {
      get { return bulletId_; }
      set {
        bulletId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BulletData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BulletData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SoilderCamp != other.SoilderCamp) return false;
      if (BulletCamp != other.BulletCamp) return false;
      if (SoilderId != other.SoilderId) return false;
      if (BulletId != other.BulletId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (SoilderCamp != 0) hash ^= SoilderCamp.GetHashCode();
      if (BulletCamp != 0) hash ^= BulletCamp.GetHashCode();
      if (SoilderId != 0) hash ^= SoilderId.GetHashCode();
      if (BulletId != 0) hash ^= BulletId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (SoilderCamp != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) SoilderCamp);
      }
      if (BulletCamp != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) BulletCamp);
      }
      if (SoilderId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(SoilderId);
      }
      if (BulletId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(BulletId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (SoilderCamp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) SoilderCamp);
      }
      if (BulletCamp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) BulletCamp);
      }
      if (SoilderId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SoilderId);
      }
      if (BulletId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BulletId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BulletData other) {
      if (other == null) {
        return;
      }
      if (other.SoilderCamp != 0) {
        SoilderCamp = other.SoilderCamp;
      }
      if (other.BulletCamp != 0) {
        BulletCamp = other.BulletCamp;
      }
      if (other.SoilderId != 0) {
        SoilderId = other.SoilderId;
      }
      if (other.BulletId != 0) {
        BulletId = other.BulletId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            SoilderCamp = (global::ProtoBulletData.BulletData.Types.CampState) input.ReadEnum();
            break;
          }
          case 24: {
            BulletCamp = (global::ProtoBulletData.BulletData.Types.CampState) input.ReadEnum();
            break;
          }
          case 32: {
            SoilderId = input.ReadInt32();
            break;
          }
          case 40: {
            BulletId = input.ReadInt32();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the BulletData message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum CampState {
        [pbr::OriginalName("red")] Red = 0,
        [pbr::OriginalName("blue")] Blue = 1,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
